spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/register-ts
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
car:
  numbers:
    A:
      - 'FF10FF'
      - 'WD-15'
      - 'FG11FF'
      - 'FG12FF'
      - 'FG13FF'
      - 'WD-16'
      - 'WD-17'
