package com.dyplom.domain.car;

public enum Brand {
    ACURA("Acura"),
    ALFAROMEO("Alfa Romeo"),
    ASTONMARTIN("Aston Martin"),
    AUDI("Audi"),
    BENTLEY("Bentley"),
    BMW("Bmw"),
    BRILLIANCE("Brilliance"),
    BUGATTI("Bugatti"),
    BUICK("Buick"),
    BYD("BYD"),
    CADILLAC("Cadillac"),
    CHANGAN("Changan"),
    CHERY("Chery"),
    CHEVROLET("Chevrolet"),
    CHRYSLER("Chrysler"),
    CITROEN("Citroen"),
    DACIA("Dacia"),
    DAEWOO("Daewoo"),
    DAIHATSU("Daihatsu"),
    DATSUN("Datsun"),
    DODGE("Dodge"),
    DONGFENG("Dongfeng"),
    EXEED("Exeed"),
    FAW("FAW"),
    FERRARI("Ferrari"),
    FIAT("Fiat"),
    FISKER("Fisker"),
    FORD("Ford"),
    FOTON("Foton"),
    GAC("GAC"),
    GAZ("GAZ"),
    GEELY("Geely"),
    GENESIS("Genesis"),
    GMC("GMC"),
    GREATWALL("Great Wall"),
    HAVAL("Haval"),
    HOLDEN("Holden"),
    HONDA("Honda"),
    HUMMER("Hummer"),
    HYUNDAI("Hyundai"),
    INFINITI("Infiniti"),
    ISUZU("Isuzu"),
    IVECO("Iveco"),
    JAC("Jac"),
    JAGUAR("Jaguar"),
    JEEP("Jeep"),
    KIA("Kia"),
    LAMBORGHINI("Lamborghini"),
    LANCIA("Lancia"),
    LANDROVER("Land Rover"),
    LEXUS("Lexus"),
    LIFAN("Lifan"),
    LINCOLN("Lincoln"),
    LOTUS("Lotus"),
    MARUSSIA("Marussia"),
    MASERATI("Maserati"),
    MAYBACH("Maybach"),
    MAZDA("Mazda"),
    MCLAREN("McLaren"),
    MERCEDES("Mercedes"),
    MERCURY("Mercury"),
    MG("MG"),
    MINI("Mini"),
    MITSUBISHI("Mitsubishi"),
    NISSAN("Nissan"),
    OPEL("Opel"),
    PEUGEOT("Peugeot"),
    PLYMOUTH("Plymouth"),
    PONTIAC("Pontiac"),
    PORSCHE("Porsche"),
    RAVON("Ravon"),
    RENAULT("Renault"),
    ROLLSROYCE("Rolls-Royce"),
    ROVER("Rover"),
    SAAB("Saab"),
    SATURN("Saturn"),
    SCION("Scion"),
    SEAT("Seat"),
    SKODA("Skoda"),
    SMART("Smart"),
    SSANGYONG("Ssang Yong"),
    SUBARU("Subaru"),
    SUZUKI("Suzuki"),
    TESLA("Tesla"),
    TOYOTA("Toyota"),
    UAZ("UAZ"),
    VOLKSWAGEN("Volkswagen"),
    VOLVO("Volvo");

    Brand(String value) {

    }
}
